### ISSUE TITLE
A little bug in darkmode feature

### ISSUE THREAD

**Issue by abhirupmjdr** [covid19india/covid19india.github.io#1893] opened 2020-05-15 10:35 UTC
**Describe the bug**
When I’m opening this website in mobile then the darkmode and daymode mixed up in the mobile page.

**To Reproduce**
You should check your codes for the dark mode again.

**Expected behavior**
Anyone of this mode should work.. either dark mode or light mode.

**Screenshots**
![FF6F84E5-64DF-4A3B-9B36-E45AE5C43407](https://user-images.githubusercontent.com/52421748/82041350-a50c6c80-96c5-11ea-88cf-a16948bfb136.png)

**Smartphone (please complete the following information):**

- Device: iPhone 6s
- OS: iOS 13
- Browser: safari

**Additional context**

**Comment by ayushya** [comment] 2020-05-15 13:43
Duplicate of https://github.com/covid19india/covid19india-react/issues/1852
Fixed with https://github.com/covid19india/covid19india-react/pull/1853

**Closed as completed** 2020-05-15 21:23 UTC
