### ISSUE TITLE
Need to show recent cases added in home page.

### ISSUE THREAD

**Issue by s-naveen** [covid19india/covid19india.github.io#110] opened 2020-03-25 15:35 UTC

**Comment by jeremyphilemon** [comment] 2020-03-25 23:10
What do you mean? There are delta values present on the header, would appreciate more information!

**Comment by s-naveen** [comment] 2020-03-26 14:58
@jeremyphilemon I meant recent cases timeline like the one shown on worldometer. 
https://prnt.sc/rn8vtt

**Comment by JunaidBabu** [comment] 2020-03-29 02:40
Duplicate of #292

**Closed as completed by JunaidBabu** 2020-03-29 02:40 UTC
Labels: Status: Review Needed
