### ISSUE TITLE
Ahmadabad showing under maharashtra state

### ISSUE THREAD

**Issue by sachinsangle8652** [covid19india/covid19india.github.io#556] opened 2020-04-02 17:58 UTC
![Screenshot_2020-04-02-23-22-56-701_com android chrome](https://user-images.githubusercontent.com/63068702/78282312-ae88ad80-7539-11ea-9622-352e2bb3958a.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hitesh-tarani** [comment] 2020-04-02 18:10
Duplicate of #553.

**Comment by sudevschiz** [comment] 2020-04-03 01:26
This has been fixed at a data end. Thanks for reporting.

**Closed as completed by sudevschiz** 2020-04-03 01:26 UTC
Labels: Status: Review Needed
