### ISSUE TITLE
Wrong District in Maharashtra

### ISSUE THREAD

**Issue by akshayjadhav9** [covid19india/covid19india.github.io#555] opened 2020-04-02 17:42 UTC
Ahemdabad District list down in Maharashtra 
Refer attached Screenshot

Steps to Reproduce : 
1. Open URL
2. Expand Maharashtra 
![Screenshot_20200402-230712__01](https://user-images.githubusercontent.com/63014676/78280834-59e43300-7537-11ea-8759-ab0372e49a56.jpg)

**Comment by hitesh-tarani** [comment] 2020-04-02 18:10
Duplicate of #553.

**Comment by yulanl22** [comment] 2020-04-02 18:10
Those two cases are of Aurangabad which is wrongly put up as 'Ahmadabad'
Also spelling under Gujarat of Ahmedabad is incorrect

**Closed as completed** 2020-04-02 18:49 UTC
Labels: Status: Review Needed
