### ISSUE TITLE
Number of active cases shown as negative in statewise data

### ISSUE THREAD

**Issue by anuragnatoo** [covid19india/covid19india.github.io#2187] opened 2020-06-25 13:10 UTC
**Number of active cases shown as negative in statewise data**
When we click on state Telangana's data its showing negative number of active cases in Unknown column. 
Also, the number of active cases in Hyderabad(which is a district/city) happens to be more than number of active cases in state Telangana.

**Expected behavior**
Number of active cases in a state should be total of all the districts/cities.
**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/35635290/85725874-2ae2f500-b713-11ea-8771-1e73408e3ced.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Comment by atmakur** [comment] 2020-06-25 21:07
Duplicate of #2186 . This issue is not with Telangana alone but couple of other states as well.

**Comment by anuragnatoo** [comment] 2020-06-26 03:55
Yes Just went through all the states data.Tamil Nadu,Gujarat,Tripura, Goa,Nagaland,Sikkim and Meghalaya also have negative values in unknown column in state wise data

**Comment by shuklaayush** [comment] 2020-06-26 07:44
This has been discussed multiple times. Please have a look at #1951

**Closed as completed by shuklaayush** 2020-06-26 07:44 UTC
Labels: Status: Review Needed
