### ISSUE TITLE
Github icon is not distinctly visible on About page in Dark mode.

### ISSUE THREAD

**Issue by dsaw** [covid19india/covid19india.github.io#2246] opened 2020-07-15 10:15 UTC
1. Open [About page]( https://www.covid19india.org/about)
2. Click on moon icon to enable dark mode
3. Scroll down and check github icon

The black github icon link is barely visible on the dark background

**Screenshots**
![giticonbarley see](https://user-images.githubusercontent.com/5353891/87533262-f8913b80-c6b1-11ea-87f2-c3b363c10de3.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version 83

The colour of the icon can be changed by modifying the opacity or so.

**Comment by balrajsingh9** [comment] 2020-07-15 11:32
Fixed in #2180 and duplicate of #2209

**Comment by dsaw** [comment] 2020-07-18 05:31
Ah right. probably can close this once its merged?

**Comment by balrajsingh9** [comment] 2020-07-18 05:54
Yes 👍

**Comment by shuklaayush** [comment] 2020-07-18 11:51
Fixed via 1a707d43ba1e31983ec3aa2020a4f49b51f59f96

**Closed as completed by shuklaayush** 2020-07-18 11:51 UTC
Labels: Status: Review Needed
