### ISSUE TITLE
Add the number of tests count in the table

### ISSUE THREAD

**Issue by yashshah1** [covid19india/covid19india.github.io#969] opened 2020-04-11 17:18 UTC
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
The number of tests is displayed on the map, it can also be displayed in the table along with other figures like confirmed, recovered etc

**Comment by bee-rickey** [comment] 2020-04-11 18:56
Duplicate of #943. Closing for now.

**Closed as completed by bee-rickey** 2020-04-11 18:56 UTC
Labels: Duplicate
