### ISSUE TITLE
Clicking on Deceased option in state page doesn't show the number in the placeholder below

### ISSUE THREAD

**Issue by DikshantYadav19** [covid19india/covid19india.github.io#1711] opened 2020-05-02 08:19 UTC
**Describe the bug**
Go to any of the state's page. Clicking on any other option except for "Deceased" shows the number but not for deceased

**To Reproduce**
Steps to reproduce the [behavior:](url)

1. Go to 'https://www.covid19india.org/state/MH'
2. Click on 'Deceased'
3. Doesn't show the number in the placeholder below

**Expected behavior**
Like all other options there, "Confirmed", "Active" and "Recovered", I expect "Deceased" too should be showing the numbers when clicked

**Screenshots**
Clicking on "Deceased", did not show the number 485 below.
![deceased_error](https://user-images.githubusercontent.com/17436526/80858874-2271bf00-8c7a-11ea-83dc-426110d122a6.PNG)

Clicking on "Recovered", showed the number 1879 below.
![recovered_Example](https://user-images.githubusercontent.com/17436526/80858875-23a2ec00-8c7a-11ea-8ebe-83d3fb55f05c.PNG)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Firefox, Chrome

**Smartphone (please complete the following information):**

- Device:Realme 3 pro
- OS: Android
- Browser Chrome

**Additional context**

**Comment by bee-rickey** [comment] 2020-05-02 11:08
This seems to be working on firefox + OSX. Need someone on android/windows to have a look before we resolve this issue. 
<img width="511" alt="Screenshot 2020-05-02 at 4 36 54 PM" src="https://user-images.githubusercontent.com/63364562/80862489-42fa4300-8c93-11ea-80ba-58c640da2dab.png">

**Comment by shubhamjain2998** [comment] 2020-05-02 11:34
Hey, @bee-rickey I think you misunderstood the issue here because as far as I can see on the website when the state page is opened and **no district** is selected then the issue persists with a deceased value like in the ss shared by @DikshantYadav19 only Maharashtra is selected and no region is selected, once you click the region it works totally fine like in the ss shared by you.

**Comment by shubhamjain2998** [comment] 2020-05-02 12:13
![Screenshot from 2020-05-02 17-37-58](https://user-images.githubusercontent.com/30628775/80863725-d0da2c00-8c9b-11ea-95a2-0cc8c343fe61.png)

The issue persists because we are showing the value of a deceased key in the object which if you can see is present in Maharashtra object as **death** that's why it's returning null, other keys active and confirmed are same in both state and district object. We can simply put a condition for checking in below line if its a State object and the deceased option are selected.

https://github.com/covid19india/covid19india-react/blob/7149f5a88a0595b138678fecd96901dfd8b31f09/src/components/mapexplorer.js#L304

**Comment by raxraj** [comment] 2020-05-07 10:59
I can confirm that the issues exist.
I believe I can solve the issue, I'm gonna try right away.

![image](https://user-images.githubusercontent.com/41513907/81287039-b3340a80-907f-11ea-9761-7bf5c7d5ceea.png)

![image](https://user-images.githubusercontent.com/41513907/81287099-d1016f80-907f-11ea-9e99-6e84c0f4d905.png)

![image](https://user-images.githubusercontent.com/41513907/81287118-da8ad780-907f-11ea-8189-cf965689a138.png)

**Comment by shuklaayush** [comment] 2020-05-17 08:06
Fixed via 9ff0278

**Closed as completed by shuklaayush** 2020-05-17 08:06 UTC
Labels: Status: Revision Needed
