### ISSUE TITLE
Active cases trend

### ISSUE THREAD

**Issue by raghavendrarai** [covid19india/covid19india.github.io#907] opened 2020-04-10 13:30 UTC
**Is your feature request related to a problem? Please describe.**
It will be good if we show the trend for active cases across the country. Currently we have only confirmed, recovered and deceased trends. This will help to understand how well the county is fighting against this battle.

**Describe the solution you'd like**
One more chart showing active cases (Total confirmed cases - Total recovered cases - Total deceased cases)

**Describe alternatives you've considered**
Can be included in the tool tip of the confirmed cases trend as well.

**Comment by raghavendrarai** [comment] 2020-04-10 13:31
It will be good if we have trend showing active cases.

**Comment by mohitm15** [comment] 2020-04-10 13:39
@raghavendrarai Clarify your issue briefly.. seems vague

**Comment by Sanskar95** [comment] 2020-04-10 14:20
Its similar to this issue 
https://github.com/covid19india/covid19india-react/issues/899
Either of them can be deleted

**Comment by bee-rickey** [comment] 2020-04-10 21:40
Duplicate of #899

**Closed as completed by bee-rickey** 2020-04-10 21:40 UTC
