### ISSUE TITLE
last updated and link for state page gets overflow when we try to see to testing stats

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2234] opened 2020-07-10 20:27 UTC
**Describe the bug**
last updated and link for state page gets overflow when we try to see to testing stats.

**To Reproduce**

1. Go to Home
2. Open district table of a state
3. Scroll right on table to see testing stats
4. Notice the error

**Expected behavior**
Position should be intact

**Screenshots**
![Screenshot (90)](https://user-images.githubusercontent.com/11428805/87200318-e57d1500-c319-11ea-91ea-668c723b9648.png)

**Comment by shuklaayush** [comment] 2020-07-10 20:50
/available
The issue is probably because [this inline](https://github.com/covid19india/covid19india-react/blob/master/src/App.scss#L1851) doesn't expand to the whole scrollable div. Not sure why that's the case.

**Comment by shuklaayush** [comment] 2020-07-18 17:39
Fixed via 2cd279a898732db88a2e5ba11037c0e55d56d195

**Closed as completed by shuklaayush** 2020-07-18 17:39 UTC
Labels: Status: Claimed
