### ISSUE TITLE
Adding smooth collpased.

### ISSUE THREAD

**Issue by Chaitanyassr** [covid19india/covid19india.github.io#1038] opened 2020-04-13 13:57 UTC
Adding smooth collpased.
smooth collapsed can be added over the tabs that mentioned states name.

**Comment by bee-rickey** [comment] 2020-04-17 09:39
Closing. This does not add any value to the cause. Please see if there are functional issues that can help the site.

**Closed as completed by bee-rickey** 2020-04-17 09:39 UTC
