### ISSUE TITLE
Age wise deceased count with male and female

### ISSUE THREAD

**Issue by rayaji** [covid19india/covid19india.github.io#1503] opened 2020-04-24 18:19 UTC
**Is your feature request related to a problem? Please describe.**

We should have one more graph in deep dive for deceased data. We can have 10 age buckets as shown in "Patient by age" graph and we should show how many of them are male and female (refer "Daily Cases" graph).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeremyphilemon** [comment] 2020-04-25 00:06
Duplicate of #967

**Closed as completed by jeremyphilemon** 2020-04-25 00:06 UTC
Labels: Status: Review Needed, Deep-Dive
