### ISSUE TITLE
Contribution guidelines has images missing.

### ISSUE THREAD

**Issue by praveenscience** [covid19india/covid19india.github.io#2390] opened 2020-12-22 09:19 UTC
**Describe the bug**
When we open the [covid19india-react/CONTRIBUTING.md at master · covid19india/covid19india-react · GitHub](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) page, the images are missing.

**To Reproduce**
Open [covid19india-react/CONTRIBUTING.md at master · covid19india/covid19india-react · GitHub](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) and you will find broken images.

**Expected behavior**
The images should be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/1830380/102871701-a27dac80-4436-11eb-9de2-8e7e3ec7f256.png)

**Comment by devkapilbansal** [comment] 2021-01-09 07:48
Duplicate of #2358

**Closed as completed** 2021-02-01 10:04 UTC
Labels: Status: Review Needed
