### ISSUE TITLE
Website home page is not working

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1350] opened 2020-04-21 04:29 UTC
**Describe the bug**
No data display on the HomePage

**To Reproduce**

1. Go to https://www.covid19india.org/

**Screenshots**
<img width="1676" alt="Screenshot 2020-04-21 at 9 57 36 AM" src="https://user-images.githubusercontent.com/21332852/79825480-bd36e780-83b6-11ea-9f7a-8740c8eebb71.png">

Desktop with google chrome browser.

**Comment by jeremyphilemon** [comment] 2020-04-21 04:30
Duplicate of #1349

**Closed as completed by jeremyphilemon** 2020-04-21 04:30 UTC
Labels: Status: Review Needed
