### ISSUE TITLE
Data not displaying in website 

### ISSUE THREAD

**Issue by anilam** [covid19india/covid19india.github.io#1352] opened 2020-04-21 05:04 UTC
Data is not displaying in website. Please check the issue.

**Comment by jeremyphilemon** [comment] 2020-04-21 05:06
Duplicate of #1349

**Comment by varunkakkar** [comment] 2020-04-21 05:06
I think it's a network issue on your side. Please post additional details

**Closed as completed by jeremyphilemon** 2020-04-21 05:06 UTC

**Comment by lakshmi14** [comment] 2020-04-21 05:10
![image](https://user-images.githubusercontent.com/7721961/79827603-692f0180-83bc-11ea-8558-4d4522751e17.png)

Clearing the browser cache and hard refresh solved the issue
