### ISSUE TITLE
Total number of tests all over india not shown

### ISSUE THREAD

**Issue by Dhrumit8596** [covid19india/covid19india.github.io#940] opened 2020-04-11 07:51 UTC
**Is your feature request related to a problem? Please describe.**
The default page shows the total number of test of Maharashtra and then you can only the the total number of tests state wise

**Describe the solution you'd like**
You can show total number of tests for default and then statewise after selecting different states.

**Comment by bee-rickey** [comment] 2020-04-11 07:52
Duplicate of #937

**Closed as completed by bee-rickey** 2020-04-11 07:52 UTC
Labels: Duplicate
