### ISSUE TITLE
Showing Data for Maharashtra instead of complete India, on right opening the website.

### ISSUE THREAD

**Issue by DashmeetArt** [covid19india/covid19india.github.io#694] opened 2020-04-05 13:05 UTC
**Describe the bug**
When a user opens the website, It shows the data which represents only data for Maharashtra, even when user didn't even hover on any of state on the map. Until user hovers on any state, It should show complete data for all India, instead only for a single state.

**To Reproduce**

1. Go to ['https://www.covid19india.org/'](https://www.covid19india.org/)
2. Scroll down to until you see map.
4. See the data showing of a single state, instead, it should show data for India not just for a single state, until a user clicks/hovers on any state.

**Expected behavior**
Show data representing India, not a state.

**Screenshots**
<img width="525" alt="Screenshot 2020-04-05 at 6 27 21 PM" src="https://user-images.githubusercontent.com/20279468/78498952-533e0180-776b-11ea-8c6c-e7ba30f61a8e.png">

**Desktop (please complete the following information):**

- OS: Any
- Browser: Any
- Version: Any

**Smartphone (please complete the following information):**

- Device: Any
- OS: Any
- Browser Any
- Version Any

**Comment by nehalb123** [comment] 2020-04-05 13:25
Working on this issue

**Comment by sumukhah** [comment] 2020-04-05 13:53
This issue is also showing up on a state map.
It will display statistics of some random region of the state.
Instead of this, it should display statistics of the entire state until a region is selected by the user.

![Screenshot from 2020-04-05 19-21-07](https://user-images.githubusercontent.com/23723464/78500202-d9aa1180-7772-11ea-9a99-fb11335a3c94.png)

**Comment by nehalb123** [comment] 2020-04-05 14:08
@sumukhah Yes, Can we have a new issue for this?

**Comment by jeremyphilemon** [comment] 2020-04-05 20:11
Hey, thanks for filing the issue! I'd like to understand why the map should show the statistics of India as a whole in the beginning given that we are already showing those stats on the primary header. 

<img width="1105" alt="Screen Shot 2020-04-05 at 11 09 24 PM" src="https://user-images.githubusercontent.com/17938322/78508844-a2e3f380-7792-11ea-946f-a73b86fba491.png">

This would just make the numbers look redundant across the screen. Having a state selected (in this case we're selecting the state with the highest number of confirmed cases) in the beginning hints to the user that the map can be used to see state specific data :)

**Comment by DashmeetArt** [comment] 2020-04-09 01:17
@jeremyphilemon , if we are showing the data for particular state of India based on number without user hovering on that, then I think we should highlight the area on map with boundaries, similar to when mouse hovers on that.
Because showing complete map, but data of particular region doesn’t make any sense, or at least add text among that data, that why that particular state’s data has been showing like `Most effected state in India` and when in state `Most effected city in Maharashtra`. If it makes sense.

**Comment by jeremyphilemon** [comment] 2020-04-17 17:30
@DashmeetArt thanks for your input. I agree with you, having the border visible always makes sense. Closing this because we decided to show "Total" stats on the homepage anyway because the graphs need to be shown for all India, and the map is synced with the data fed to graph 🤷

**Closed as completed by jeremyphilemon** 2020-04-17 17:30 UTC
Labels: Status : Question
