### ISSUE TITLE
Leverage the use of tooltip

### ISSUE THREAD

**Issue by atmanikumar** [covid19india/covid19india.github.io#2310] opened 2020-08-08 16:06 UTC
**Is your feature request related to a problem? Please describe.**
No, But This will help user to understand more on what are all features available currently on platform. 

Currently in many places we do have icon as button interface, example

<img width="1217" alt="Screenshot 2020-08-08 at 9 00 29 PM" src="https://user-images.githubusercontent.com/24696060/89714315-4fd9b180-d9bb-11ea-9770-5c1943892c72.png">

To get to know the purpose these icons or buttons, User supposed to click on those elements and see the usage of it. Example As a daily user, I came to know only today that there is history of results available, Where we can see previous days results as tabular view just clicking on this Icon (shown in below image).  A big feature hiding on small icon.

<img width="615" alt="Screenshot 2020-08-08 at 8 52 32 PM" src="https://user-images.githubusercontent.com/24696060/89714334-5bc57380-d9bb-11ea-9d3f-8d4d09a60db2.png">

**Describe the solution you'd like**

There could be many solutions for this, But I'm suggesting to show `tooltip` on hover state and placing top of those Icons to let user know, What features are behind those elements. It saves many number of user clicks on icons to just get to know what these icon does. 

example

<img width="363" alt="Screenshot 2020-08-08 at 9 29 43 PM" src="https://user-images.githubusercontent.com/24696060/89714714-53226c80-d9be-11ea-9e93-b2dafc5e464f.png">

I can understand that Icons are preferred here to avoid space limitation in mobile device. But If users for this platform is more from Desktop then we can have media query to implement this feature only on Desktop.

**Describe alternatives you've considered**

We can also go with button text with Icon prefixed as shown below. But prefer tooltip as first solution.

<img width="265" alt="Screenshot 2020-08-08 at 9 23 10 PM" src="https://user-images.githubusercontent.com/24696060/89714594-73056080-d9bd-11ea-915d-b94bc845e8f5.png">

**Additional context**

**Comment by bmnidhin** [comment] 2020-08-09 13:34
In this era 90% of users may use mobile phones over desktop/laptop. Therefore a tooltip may not help mobile users. I think a **button label**  is useful. 

But icons may speak for itself. Huh?

**Comment by bee-rickey** [comment] 2020-08-20 19:27
Duplicate of #2295

**Closed as completed by bee-rickey** 2020-08-20 19:27 UTC
Labels: Status: Review Needed
