### ISSUE TITLE
Active and recovered cases for district wise data

### ISSUE THREAD

**Issue by DDGudu** [covid19india/covid19india.github.io#1470] opened 2020-04-23 21:05 UTC
**Is your feature request related to a problem? Please describe.**
District wise data for the currently actively cases and total confirmed cases should be present when clicked on the drop down beside the states

**Comment by jeremyphilemon** [comment] 2020-04-23 22:31
Duplicate of #675

**Closed as completed by jeremyphilemon** 2020-04-23 22:31 UTC
Labels: Status: Review Needed
