### ISSUE TITLE
Area of hover district not showing in the map

### ISSUE THREAD

**Issue by shubhids** [covid19india/covid19india.github.io#388] opened 2020-03-30 10:45 UTC
**Describe the bug**
Some district area are not showing in the map.

**To Reproduce**

1. Click on the Maharashtra state.
2. Hover the district AHMADNAGAR.
3. See the map.

**Expected behavior** 
Should show the area of district in the map like other district.
![Screenshot from 2020-03-30 16-04-29](https://user-images.githubusercontent.com/2937723/77903982-64859a80-72a1-11ea-989f-fb163e721a26.png)

**Screenshots**
![Screenshot from 2020-03-30 16-03-39](https://user-images.githubusercontent.com/2937723/77904077-8848e080-72a1-11ea-98a2-ebf591453f00.png)

**Comment by Nitin96Bisht** [comment] 2020-03-30 11:02
@jeremyphilemon @JunaidBabu @sudevschiz Kindly check the above pull request.

**Comment by rakeshreddy1410** [comment] 2020-03-30 11:06
The issue is with the mismatch of data from **state_district_wise.json** and **state.json**
one has name as **Ahmednagar** and the other **Ahmadnagar**
There are many other districts with the similar issue

**Comment by Nitin96Bisht** [comment] 2020-03-30 16:38
@rakeshreddy1410 I have checked all districts. We don't have any more like it.

**Comment by rakeshreddy1410** [comment] 2020-03-30 17:30
> @rakeshreddy1410 I have checked all districts. We don't have any more like it.

Check telangana.json

**Comment by Nitin96Bisht** [comment] 2020-03-30 18:18
@rakeshreddy1410 kindly check it.

**Comment by shuklaayush** [comment] 2020-04-01 05:11
Fixed via #429

**Closed as completed by shuklaayush** 2020-04-01 05:11 UTC
Labels: Status: Review Needed, Geography
