### ISSUE TITLE
Display of district wise active cases

### ISSUE THREAD

**Issue by priya90rw8l** [covid19india/covid19india.github.io#1379] opened 2020-04-21 18:47 UTC
**Is your feature request related to a problem? Please describe.**

Currently we see district level confirmed cases. It will be good to show active cases at district level for more awareness of the current situation.

**Describe the solution you'd like**
For active cases, a filter needs to be put at district level.

**Describe alternatives you've considered**
Adding a column next to the cases will help to understand the current situation of the district to take decision at district level. Might help to review the current situation and relaxation from lockdown which leads to Indian economy.

**Comment by jeremyphilemon** [comment] 2020-04-21 23:07
Duplicate of #675, please refer to the discussions of said issue

**Closed as completed by jeremyphilemon** 2020-04-21 23:07 UTC
Labels: Status: Review Needed
