### ISSUE TITLE
opening dropdown for state.

### ISSUE THREAD

**Issue by Binu42** [covid19india/covid19india.github.io#620] opened 2020-04-04 01:45 UTC
**Is your feature request related to a problem? Please describe.**
currently user can open dropdown as many they wish to. which make the page very long in mobile view which is frustrating for users and even in desktop view after opening dropdown for 2-3 states, users are not able to see the map view of state. one more problem, on hover of rows alternate rows doesn't show any effect which look like it's not clickable.

**Describe the solution you'd like**
i want to allow users to open only one dropdown of state. like if, already one dropdown is open, then automatically close that one before opening of newer one. and for dropdown i'll change some style to give it better look on hover.

**Describe alternatives you've considered**
i have already worked on the solution which i described, it's working well. if it's get accepted, i will raise pull request.

**Additional context**
###### present situation
![beforgify](https://res.cloudinary.com/dykt1kcdk/image/upload/v1585964174/before_dropdown_nzsuux.gif)
<br>

###### after solving it.
![aftergify](https://res.cloudinary.com/dykt1kcdk/image/upload/v1585964149/after_dropdown_zjewpc.gif)

**Comment by sudevschiz** [comment] 2020-04-04 03:24
This would be a nice enhancement. Making this available :)

**Comment by shngt** [comment] 2020-04-04 05:29
This could be annoying for people who wish to compare districts in different states, like when you want to look out for family members scattered over India. Maybe limit the number of tabs you can have open to something like 3 or 4?

**Comment by jainprashul** [comment] 2020-04-04 05:33
Well , we can use accordian here for this . @Binu42

**Comment by Binu42** [comment] 2020-04-04 06:12
@sudevschiz can you please assign it to me.

**Comment by shuklaayush** [comment] 2020-04-04 06:25
Duplicate of #326. Please go through that discussion as well

**Closed as completed** 2020-04-04 07:13 UTC
Labels: Status: Available

**Comment by bharadwaja1297** [comment] 2020-04-04 09:38
That's great...opening dropdown for state.
