### ISSUE TITLE
City level choropleth maps for reported cases

### ISSUE THREAD

**Issue by elseasama** [covid19india/covid19india.github.io#596] opened 2020-04-03 14:53 UTC
**Is your feature request related to a problem? Please describe.**
A city level map of the number of reported cases will be of the most use to users than state level or district level maps. This is especially true for the major metro cities (i.e. Mumbai, Chennai, Delhi, Kolkata etc.). This will allow for easy visualization of areas to avoid during the outbreak.

**Describe the solution you'd like**
Use the reported cases in a city by zone wise to create the choropleth map.

geojson files for Chennai and Mumbai city from [here](https://github.com/mickeykedia/India-Maps ).
Official statistics for total confirmed cases published by the city corporations.

**Describe alternatives you've considered**
Dot-intensity or graduated circle map to visualize the hotspots of the number of cases.

**Additional context**
![photo_2020-04-03_19-49-32](https://user-images.githubusercontent.com/17410369/78373539-5c529580-75e8-11ea-9fe2-bf261367177a.jpg)

**Comment by sudevschiz** [comment] 2020-04-04 03:19
This would be a huge activity - from a data standpoint as well as a geoJSON standpoint.
Opening this up with Low Priority

**Comment by elseasama** [comment] 2020-04-16 10:03
I have both the city level geojson data and the data case data. Have been doing for more than a week now everyday. 
![16-04-201](https://user-images.githubusercontent.com/17410369/79443481-8009d880-7ff7-11ea-8250-8db7ddcb418b.png)

**Comment by shuklaayush** [comment] 2020-04-16 10:36
@elseasama Can you share those along with a source of the data?

**Comment by elseasama** [comment] 2020-04-16 10:58
[Ward and zone case data](https://docs.google.com/spreadsheets/d/1-SUs7yJeJzYQMNbH6ERPReV0ua9bDHZtb_uHqbEPeI8/edit?usp=sharing)


[Chennai zone and ward level geojson file](https://github.com/elseasama/chcovid19/blob/master/Chennai.geojson)

[Chennai containment zone map](https://github.com/elseasama/chcovid19/blob/master/containmentzone.geojson)

**Comment by elseasama** [comment] 2020-04-16 13:02
The containment zone map has been completed.

**Comment by elseasama** [comment] 2020-04-17 19:41
the source of the data is from the Greater Chennai corporation [twitter feed](https://twitter.com/chennaicorp).

**Comment by jeremyphilemon** [comment] 2020-04-17 22:45
cc @sudevschiz @bee-rickey

**Comment by bee-rickey** [comment] 2020-04-18 18:32
@elseasama hello, are the geojson files available for other cities as well? Or do you have it just for Chennai as of now?

**Comment by bee-rickey** [comment] 2020-04-18 18:44
Anyone looking at this issue, here's a [nice datameet source ](https://github.com/datameet/Municipal_Spatial_Data)with some geojsons for certain cities. Not sure how accurate these are now though.

**Comment by elseasama** [comment] 2020-04-18 19:18
> @elseasama hello, are the geojson files available for other cities as well? Or do you have it just for Chennai as of now?
I have made just for Chennai since I had the verified data source and as far I am aware of, it is the only City published data by zones on a daily basis.



> Anyone looking at this issue, here's a nice datameet source with some geojsons for certain cities. Not sure how accurate these are now though.

Looks pretty good to me for the major cities at least.

**Comment by jeremyphilemon** [comment] 2020-04-18 19:59
@elseasama I think this would be a good start for incorporating city level granularity into the stats. And since you're using a verifiable source for the data, we can get started.

The twitter feed must be input into the sheets and updated timely for the api. And then someone can take up incorporating a district level page. (Adding districts to the existing map on the homepage would make the code really complex so a separate page would be a good start). Let me know if anyone would like to take this up, I can work alongside to get this pushed :)

**Comment by elseasama** [comment] 2020-04-19 17:09
@jeremyphilemon 
Added recovered ,Hospitalized, and deceased sheet.
Added Sex and age wise distribution sheet.
Added source sheet.

[Google sheets](https://docs.google.com/spreadsheets/d/1-SUs7yJeJzYQMNbH6ERPReV0ua9bDHZtb_uHqbEPeI8/edit?usp=sharing)  


Also mapped the containment zones and streets in the city using official data list.

 [Link to the map](https://elseasama.github.io/chcovid19/)

**Comment by jeremyphilemon** [comment] 2020-04-21 22:58
> Ward / City level information is simply too sparse to collect.
> 
> We will try to add details regarding the Red-Yellow-Green zones. This is being worked on in this sheet. https://docs.google.com/spreadsheets/d/1A-9EDpiD6vxSaCCa9yYwTRKiNwoJ2hdxjbQkmw_RgTA/edit#gid=0
> 
> Please do comment there and help us create a template for the data.
- @sudevschiz 

Putting this here for reference. Also cc @sudevschiz, checkout the recent comments.

**Comment by aTrueSeeker** [comment] 2020-05-10 10:02
> @elseasama I think this would be a good start for incorporating city level granularity into the stats. And since you're using a verifiable source for the data, we can get started.
> 
> The twitter feed must be input into the sheets and updated timely for the api. And then someone can take up incorporating a district level page. (Adding districts to the existing map on the homepage would make the code really complex so a separate page would be a good start). Let me know if anyone would like to take this up, I can work alongside to get this pushed :)

I would like to take this up

**Comment by elseasama** [comment] 2020-06-08 05:47
@jeremyphilemon @aTrueSeeker I have made APIs and CSV data files available for Chennai city. Hopefully it will be useful. 
geojson for Chennai city by zones: https://github.com/elseasama/covid19chennai/blob/gh-pages/chennai_data/geojson/Chennai_Zones.geojson

API and csv data file link: https://github.com/elseasama/covid19chennai/blob/gh-pages/README.md

**Comment by Keertesh** [comment] 2020-06-15 05:48
> @elseasama I think this would be a good start for incorporating city level granularity into the stats. And since you're using a verifiable source for the data, we can get started.
> 
> The twitter feed must be input into the sheets and updated timely for the api. And then someone can take up incorporating a district-level page. (Adding districts to the existing map on the homepage would make the code really complex so a separate page would be a good start). Let me know if anyone would like to take this up, I can work alongside to get this pushed :)

I can also provide some support to whoever is working on this. (like Updating Geographic information on the map, updating components in the react source)

**Comment by Mayank-Sh07** [comment] 2020-07-24 08:21
@elseasama @sudevschiz @jeremyphilemon  I'm a bit new to React, Github and app-dev in general but during this lockdown I utilized my time to learn some Javascript and using the React library I've made an app which I feel is kinda relatable in the scope of this issue

app link: "SAFEZONE" -> https://safezone-ch.web.app/
do check it out (make sure to reset origin to some location in chennai to see the Covid visualisations)
It's only for Chennai

Currently I'm using the covid19India (https://api.covid19india.org/state_district_wise.json) endpoint to display the active and confirmed cases for chennai but all the case points I've shown within the marker-clusters are Randomized since I couldn't find any concrete location data (latlngs)for the cases , If my app ideas seem like they could possibly be incorporated into the main (react) dashboard , suppose by using some other metrics for determining the zone color (possibly something from your API) 
and maybe dropping the feature of displaying the exact case locations because latlng data isn't gonna be released by Aarogya Setu/ MyGov.in
It would definitely add a lot of value in terms of travel safety and preventing the further spread of covid-19.

**Comment by bee-rickey** [comment] 2020-07-24 19:17
@Mayank-Sh07 Great work! Also, closing this issue since we do not have any plans of showing district/city level data due to the lack of data.

**Closed as completed by bee-rickey** 2020-07-24 19:17 UTC
Labels: Status: Completed, Data
