### ISSUE TITLE
Can improve visuality of left & right section

### ISSUE THREAD

**Issue by rishiip** [covid19india/covid19india.github.io#341] opened 2020-03-29 16:20 UTC
**Is your feature request related to a problem? Please describe.**
Have a look at following snapshot, there's no gap between them and it looks too close to each other - 
<img width="1280" alt="Screenshot 2020-03-29 21 44 50" src="https://user-images.githubusercontent.com/7964257/77854307-2fc50500-7207-11ea-9756-0214d191d6b9.png">

**Describe the solution you'd like**
Can add 10px or 20px space between them

**Additional Information**
I am using -
- MacOS Mojave
- Google Chrome - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by sijusamson** [comment] 2020-03-29 16:36
@rishiip Is there any way to reproduce thus, as i wasn't able to reproduce this issue. please see the attached screenshot.
![Screenshot from 2020-03-29 22-04-33](https://user-images.githubusercontent.com/38852547/77854707-7156af80-7209-11ea-980c-93d8ed2fabe0.png)

**Comment by rishiip** [comment] 2020-03-29 16:38
@sijusamson Ah, forgot to mention my system config - 

I am using -
MacOS Mojave
Google Chrome - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by sijusamson** [comment] 2020-03-29 16:41
Okay, it seems to be a system specific issue, :-)

**Comment by KrishnaPravin** [comment] 2020-04-02 02:58
@rishiip could you please check again.
I was also facing this issue in macOS Catalina with Chrome. But it seems to be fixed now.
My Chrome Version - 80.0.3987.162 (Official Build) (64-bit)

**Closed as completed** 2020-04-03 18:28 UTC
Labels: Status: Review Needed
