### ISSUE TITLE
No. of  patient confirm,recovered and deceased showing for the state we can also show for perticular district too

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#888] opened 2020-04-10 05:08 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudevschiz** [comment] 2020-04-11 19:57
Not all states provide information regarding recovery and deaths at a state level. We are working on improving the data to have this info.

Data needs to be cleansed and made available before this can be worked on.

**Comment by ravigaggad** [comment] 2020-04-13 05:13
Maximum States are giving info about recovery to.

**Comment by jeremyphilemon** [comment] 2020-04-21 22:54
Closing cause duplicate of #675

**Closed as completed by jeremyphilemon** 2020-04-21 22:54 UTC
Labels: Status: On Hold, Data
