### ISSUE TITLE
[Mobil-UI]State table and chart overflow from right side in the mobile view

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1119] opened 2020-04-15 11:18 UTC
**Describe the bug**
State/UT table and summary chart having some extra space in the right side.

**To Reproduce**

1. Open google chrome browser in the mobile.
2. Go to https://www.covid19india.org/
3. Go to state/UT table
4. Go to the summary chart

**Expected behavior**
State/UT table and summary chart should be properly fixed on the screen. Overflow not expected. In-case of overflow(Width is extended to the screen ) then the scroll option should be populated.

**Screenshots**
![WhatsApp Image 2020-04-15 at 4 41 55 PM (1)](https://user-images.githubusercontent.com/21332852/79331297-91d87680-7f38-11ea-8d1f-410ec746eaaf.jpeg)

![WhatsApp Image 2020-04-15 at 4 41 55 PM](https://user-images.githubusercontent.com/21332852/79331381-ad438180-7f38-11ea-86f2-a9e33c10deac.jpeg)

**Smartphone (please complete the following information):**

- Device: Vivo V9
- OS: Android
- Browser Google Chrome
- Version 80.0.3087.149

**Comment by Binu42** [comment] 2020-04-15 15:13
Duplicate of #1006, #951 and this bug is fixed in PR #957

**Comment by jeremyphilemon** [comment] 2020-04-16 09:21
Closing cause duplicate.

**Closed as completed by jeremyphilemon** 2020-04-16 09:21 UTC
Labels: Status: Review Needed
