### ISSUE TITLE
GitHub icon is not visible in dark mode in the Footer of the About section 

### ISSUE THREAD

**Issue by lopeselio** [covid19india/covid19india.github.io#2252] opened 2020-07-18 00:54 UTC
**Describe the bug**
GitHub icon is not visible in dark mode in the Footer of the About section 
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

1. Go to 'https://www.covid19india.org/about'
2. Switch to dark mode
3. Scroll down to the footer below
4. See error - GitHub icon is not visible in dark mode in the Footer of the About section 

**Expected behavior**
As soon as switching the page to dark mode, the color of all footer icons should also change to enhance visibility. The black github logo is not visible in the dark mode. Most users prefer dark mode, especially at night, since dark mode has become a trend nowadays. Developers willing to contribute to the project will find it difficult to locate the link to the github repo.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux Mint 19.3]
- Version [ 84.0.4147.89 (Official Build) (64-bit]

**Smartphone (please complete the following information):**

- Device: [e.g. OPPO f11 Pro]
- OS: [e.g. Android]
- Browser [e.g. Google Chrome]
- Version [ 84.0.4147.89 (Official Build) (64-bit]

**Additional context**
Tweaks
![githubicon](https://user-images.githubusercontent.com/43913734/87840841-56df3980-c8bf-11ea-9193-366cf2f998b0.png)
 for dark mode
https://css-tricks.com/dark-mode-favicons/
`<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
  <style>
    circle {
      fill: yellow;
      stroke: black;
      stroke-width: 3px;
    }
    @media (prefers-color-scheme: dark) {
      circle {
        fill: black;
        stroke: yellow;
      }
    }
  </style>
  <circle cx="50" cy="50" r="47"/>
</svg>`

**Comment by bijankundu** [comment] 2020-07-18 05:59
@balrajsingh9 has fixed it in #2180  and duplicate of #2209 and #2246

**Comment by shuklaayush** [comment] 2020-07-18 11:51
Fixed via 1a707d43ba1e31983ec3aa2020a4f49b51f59f96

**Closed as completed by shuklaayush** 2020-07-18 11:51 UTC
Labels: Status: Review Needed
