### ISSUE TITLE
Active delta at top summary does not match with the one in table total row.

### ISSUE THREAD

**Issue by s-naveen** [covid19india/covid19india.github.io#188] opened 2020-03-26 14:43 UTC
**Describe the bug**
Active delta at top summary does not match with the one in table total row

**Screenshots**
https://prnt.sc/rn8jkp

**Comment by rohit2sharma95** [comment] 2020-03-26 15:03
May I fix this issue @s-naveen? We can show the data from first index of the statewise array that is being used in the total also. See the images:-

![image](https://user-images.githubusercontent.com/26922866/77661619-e2dff500-6fa0-11ea-8ab7-c48217f2bc6a.png)

**Comment by s-naveen** [comment] 2020-03-26 15:11
@rohit2sharma95 that's what is already used. I guess its a bug in API confirmed delta also has mismatch now.

**Comment by rohit2sharma95** [comment] 2020-03-26 15:18
@s-naveen Delta in the Level component is being shown from the first index of key_values array:-
![image](https://user-images.githubusercontent.com/26922866/77663160-c2b13580-6fa2-11ea-9707-66a79e630939.png)
Whenever the proper data is at the first index of the statewise array that is not being used in the Level component:-
![image](https://user-images.githubusercontent.com/26922866/77663370-fe4bff80-6fa2-11ea-86d5-7dd5c9d00623.png)

Let me know if it is right?

**Comment by s-naveen** [comment] 2020-03-26 15:22
I am not sure the one in the key_values json or statewise json first key is correct. Can you check it yourself.

**Comment by rohit2sharma95** [comment] 2020-03-26 15:24
Okay, @s-naveen. I have checked the data manually. Let me give a pull request immediately.

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-26 15:54
@rohit2sharma95 : I think we have to either point all 'Confirmed', 'Active', 'Recovered' and 'Deceased' to not to point to 'key_values'.. I think this should be api fix not client side.. Open for suggestions..

**Comment by rohit2sharma95** [comment] 2020-03-26 16:08
@Rajesh-Narayanappa87 I have fixed the issue by showing the data the same as the total row at the bottom of the table. And if you will see the total is correct there.

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-26 16:13
@rohit2sharma95 : Did you had a chance to look into recover data.. Since first array has "recovered": 0. , graph will be flat.. Check snapshot below..
This still seems service fix.. If we refer state[0] then recovered data is incorrect. 
If we refer key_values then active calc is incorrect.. 
 
<img width="594" alt="Screenshot 2020-03-26 at 9 42 54 PM" src="https://user-images.githubusercontent.com/25228632/77669462-cea0f580-6faa-11ea-9612-f2e516d3f967.png">

**Comment by rohit2sharma95** [comment] 2020-03-26 16:30
@Rajesh-Narayanappa87 Looks good to me. If the data is shown from statewise array.
https://covid19india-react-git-fork-rohit2sharma95-master.covid19india.now.sh/

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-26 16:46
@rohit2sharma95 : Can you attach snap?? I've looked through.. found simpler fix.. For pulling active case alone, we can parse through statewise array.. This means 
line 45 in level.js will be replaced 
from 
`        <h4>[{props.deltas ? props.deltas.confirmeddelta-props.deltas.recovereddelta-props.deltas.deceaseddelta >=0 ? '+'+(props.deltas.confirmeddelta-props.deltas.recovereddelta-props.deltas.deceaseddelta).toString() : props.deltas.confirmeddelta-props.deltas.recovereddelta-props.deltas.deceaseddelta : ''}]</h4>
`
to 
`        <h4>[{props.data ? props.data[0] ? '+'+ props.data[0].delta.active : '' : ''}]</h4>
`

What do you say?

much simpler change..

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-26 17:17
#199

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-26 17:18
https://github.com/covid19india/covid19india-react/pull/199

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-26 17:19
#199

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-26 17:24
@s-naveen , @rohit2sharma95 : See if this helps..

**Comment by rohit2sharma95** [comment] 2020-03-26 17:39
@Rajesh-Narayanappa87 Please check [this comment](https://github.com/covid19india/covid19india-react/pull/199#issuecomment-604569718).

**Comment by JunaidBabu** [comment] 2020-03-27 07:57
This was an issue with the data itself. We do not have the statewise data for active/recovered/deceased. So decided not to show them in statewise table.

Closing this issue.

**Closed as completed by JunaidBabu** 2020-03-27 07:57 UTC

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-27 13:23
oh man. My first ever PR..  :(

**Comment by jeremyphilemon** [comment] 2020-03-28 04:59
@Rajesh-Narayanappa87 Hey, that's alright! I've had many PRs closed too during my first try but it's always been a learning experience! Hoping to see more PRs opened from you, head over to issues and feel free to open one from the accepted issues :)
