### ISSUE TITLE
Add graph for states. 

### ISSUE THREAD

**Issue by faizan346** [covid19india/covid19india.github.io#759] opened 2020-04-07 11:07 UTC
Additional feature. 
  Plz add graph for states which shows daily increase in cases, recovered cases and deceased cases for state. Just like the graph for whole india. When we tap on state in indian map, show corresponding graphs.

**Comment by shuklaayush** [comment] 2020-04-07 11:16
Duplicate of #564

**Closed as completed by shuklaayush** 2020-04-07 11:16 UTC
Labels: Status: Review Needed
