### ISSUE TITLE
Gujarat is displaying inside Maharashtra

### ISSUE THREAD

**Issue by whitehatrt** [covid19india/covid19india.github.io#718] opened 2020-04-06 05:56 UTC
**Bug**
Gujarat is displaying inside Maharashtra
**Steps to Reproduce:**

1. Open URL
2. Expand Maharashtra
**See Screenshot Below**
![image](https://user-images.githubusercontent.com/58036570/78532615-2f2efe80-7805-11ea-8d1a-07d872fa1a79.png)

**Comment by klakho0400** [comment] 2020-04-06 07:06
first of all it is Gujarat secondly mention which os or browser are you on for me in chrome it is fine

**Comment by whitehatrt** [comment] 2020-04-06 07:07
i am also on chrome latest version and using windows 10 os

**Comment by kavishdahekar** [comment] 2020-04-06 08:58
I can confirm the bug occurs for me too (win 10 + chrome + firefox).
Doesn't seem to be OS or browser specific.

I'd like to take this up.

According to the [contribution guide](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md), can this be marked accepted and assigned to me?

**Comment by whitehatrt** [comment] 2020-04-06 09:06
It Is the issue with the API in API data is not proper. I tried to call API.

**Comment by kavishdahekar** [comment] 2020-04-06 09:35
@whitehatrt yes! Seems to be coming from the API.
Is the API handled in a separate repo? How do we propose corrections to the API?

**Comment by whitehatrt** [comment] 2020-04-06 09:43
@kavishdahekar Here is the api https://github.com/covid19india/api

**Comment by akshayjadhav9** [comment] 2020-04-06 10:21
Otherwise give legend description against *

**Comment by kaushal7005** [comment] 2020-04-06 17:17
Change district name at Crowdsourced Patient Database -> Row_Data

Row no: 
849
27/03/2020 |   |   | Mumbai | Gujarat* | Maharashtra
to
27/03/2020 |   |   | Mumbai | Mumbai  | Maharashtra

3030
04/04/2020 |   |   |   | Gujarat* | Maharashtra
to
04/04/2020 |   |   |   | Unknown | Maharashtra

**Comment by kavishdahekar** [comment] 2020-04-06 19:25
Thanks @kaushal7005 , have requested access to edit the sheet.
I had a few questions - Does the api fetch all the data from the excel sheet? Is this done periodically? Where's the code that fetches the data from the sheet and writes them to the json files in the api repo?

**Comment by kaushal7005** [comment] 2020-04-07 06:50
**@kavishdahekar** No, I have no permission to edit the sheet.
Ans:-
yes, API fetches all the data from the excel sheet.
Sheets updated automatically every 5 minutes.
There is backend repo available https://github.com/covid19india/api.git

**Comment by kavishdahekar** [comment] 2020-04-07 11:09
Thanks @kaushal7005 
But I don't see the code in the [api repo](https://github.com/covid19india/api.git) that pulls the google sheets data.

**Comment by shuklaayush** [comment] 2020-04-11 08:42
Seems to be fixed now

**Closed as completed by shuklaayush** 2020-04-11 08:42 UTC
Labels: Status: In Progress
