### ISSUE TITLE
Total recovered cases are more than the confirmed cases.

### ISSUE THREAD

**Issue by priya90rw8l** [covid19india/covid19india.github.io#1766] opened 2020-05-04 12:43 UTC
**Describe the bug**
Recovered cases can not be more than confirmed cases.

**To Reproduce**
1. Go to 'https://www.covid19india.org/'
2. Click on 'Kerala'
3. Scroll down to 'Kozhikode'

**Expected behavior**
Recovered cases should always be less than then confirmed cases.

**Screenshots**

**Desktop (please complete the following information):**

- Browser [e.g. chrome]
![Screenshot 2020-05-04 at 6 07 16 PM](https://user-images.githubusercontent.com/17856723/80966845-ee8dc980-8e32-11ea-8cb0-2a6bb89c4798.png)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by justinsamuel92** [comment] 2020-05-04 13:40
This seems to be a duplicate of https://github.com/covid19india/covid19india-react/issues/1765

**Comment by bee-rickey** [comment] 2020-05-04 14:13
Duplicate of #1765

**Closed as completed by bee-rickey** 2020-05-04 14:13 UTC
Labels: Status: Review Needed
