### ISSUE TITLE
Detail Map not present for Puducherry

### ISSUE THREAD

**Issue by rohitaneja91** [covid19india/covid19india.github.io#720] opened 2020-04-06 06:27 UTC
**Describe the bug**
Done a Mouser Hover on Puducherry, System is not showing a detail Map it and a district affected

**To Reproduce**

1. Go to '.https://www.covid19india.org/.'
2. Click on 'State/UT', it will sort the State/UT Column 
3. Scroll down to Puducherry UT
4. Mouse Hover the Puducherry 

**Expected behavior**
Detail Map of Puducherry is not present
User click on MAHE district, system should show a District map in More details

**Desktop (please complete the following information):**
Windows 10
Chrome browser

**Comment by shuklaayush** [comment] 2020-04-06 09:31
Duplicate of #674

**Closed as completed by shuklaayush** 2020-04-06 09:31 UTC
Labels: Status: Review Needed
