### ISSUE TITLE
City Level Report

### ISSUE THREAD

**Issue by 0xbhvn** [covid19india/covid19india.github.io#1466] opened 2020-04-23 19:50 UTC
People should be able to see their city level data.

**Solution**
We can have a handful of volunteers in each city which can collect the data from their local authority. Every municipal corporation issues a report per day.

**Alternatives**
I am in the process of making our level website inspired by covid19tracker.org

It would make this website very personal to each and every person and maybe we can increase contribution from people in terms of donations to government, helping hand to underprivileged people etc.

**Comment by jeremyphilemon** [comment] 2020-04-23 22:33
Duplicate of #596

**Closed as completed by jeremyphilemon** 2020-04-23 22:33 UTC
Labels: Status: Review Needed
