### ISSUE TITLE
Add reproduction number tracking for each state

### ISSUE THREAD

**Issue by idris15** [covid19india/covid19india.github.io#1432] opened 2020-04-23 03:51 UTC
[https://rt.live/](url) tracks the evolution of reproduction number R<sub>t</sub> for each state in the US. The reproduction number is used as a very important epidemiological measure to track whether the containment measures are working or not.

The source code used to generate the necessary data (along with a very good explanation of the math behind the calculation) is provided at [https://github.com/k-sys/covid-19/blob/master/Realtime%20R0.ipynb](url).

You already have a very informative dashboard at [https://www.covid19india.org/](url) and this would be a great addition.

Thanks!

**Comment by keshank** [comment] 2020-04-23 08:27
Dublicate 
https://github.com/covid19india/covid19india-react/issues/1084

**Comment by bee-rickey** [comment] 2020-04-23 09:47
Closing. Dupe of https://github.com/covid19india/covid19india-react/issues/1084

**Closed as completed by bee-rickey** 2020-04-23 09:47 UTC
Labels: Deep-Dive
