### ISSUE TITLE
Disable 'Change Active State' on hover. make it on click.

### ISSUE THREAD

**Issue by Sumanta9x9** [covid19india/covid19india.github.io#1286] opened 2020-04-19 08:44 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tshrwbl** [comment] 2020-04-19 09:08
Do you mean #1243 ?

**Comment by JunaidBabu** [comment] 2020-04-19 13:16
Duplicate of #1243

**Closed as completed by JunaidBabu** 2020-04-19 13:16 UTC
Labels: Status: Review Needed
