### ISSUE TITLE
npm i && npm start does not work in windows 

### ISSUE THREAD

**Issue by Nitin96Bisht** [covid19india/covid19india.github.io#241] opened 2020-03-27 17:31 UTC
**Describe the bug**
When I `npm i && npm start` as mentioned in README file. It gives error.

**To Reproduce**
1. Clone project
2. Go to project directory
3. Run `npm i && npm start`

**Expected behavior**
It should run the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/23516674/77782032-a255a980-707c-11ea-93a7-cfbfb4bfcf44.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.149

**Comment by s-naveen** [comment] 2020-03-27 17:41
Try running this command then start (haven't tested it myself)

npm --add-python-to-path='true' --debug install --global windows-build-tools

**Comment by Nitin96Bisht** [comment] 2020-03-27 19:02
@s-naveen it does not work. Can somebody help me out? I want to be part of this and contribute.

**Comment by s-naveen** [comment] 2020-03-27 19:08
@Nitin96Bisht Its probably something do with python installation in your system. Its either not installed or environment variable not set.

**Comment by d3v7** [comment] 2020-03-27 20:07
Right click on my computer (THIS PC) > Advanced system settings > In Advanced Tab > Environment Variables > In system variables look for the variable PATH > click Edit > click New then Add your python installed location
e.g: C:\Program Files (x86)\Python37-32\

**Comment by Rajanpandey** [comment] 2020-03-27 20:20
Duplicate of https://github.com/covid19india/covid19india-react/issues/171
Already fixed with: https://github.com/covid19india/covid19india-react/pull/177

**Comment by d3v7** [comment] 2020-03-27 20:36
I am getting this error


PORT' is not recognized as an internal or ex operable program or batch file.

npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! Covid@e.1.0 Sart: `PORT=3001 react!

npm ERR! Exit status 1 npm ERR!

npm ERR! Failed at the covid@e.1.0 start scri npm ERR! This is probably not a problem with

**Comment by jeremyphilemon** [comment] 2020-03-27 23:24
Closing cause #177. Feel free to reopen the issue if you're still facing issues.

**Closed as completed by jeremyphilemon** 2020-03-27 23:24 UTC
Labels: Status: Review Needed

**Comment by Nitin96Bisht** [comment] 2020-03-28 17:11
@jeremyphilemon I have already referred #177 as it did not work out and I have also added Python path. Hence I created an issue. I think setup documentation needs to be updated for Windows users with all prerequisites along with possible errors and their resolutions. 

Secondly I am unable to reopen it. Can you please reopen?
