### ISSUE TITLE
Clicking on the row in the table not opening respective city details

### ISSUE THREAD

**Issue by jitesh-trivedi** [covid19india/covid19india.github.io#1181] opened 2020-04-16 16:40 UTC
Expanding the tablenrow is only limited to click on expand icon. Clicking on the row also should expand details containing city related details

**Comment by abhishekakade** [comment] 2020-04-17 09:59
Possible duplicate of #1180

**Comment by jeremyphilemon** [comment] 2020-04-17 10:17
Patched :)

**Closed as completed by jeremyphilemon** 2020-04-17 10:17 UTC
