### ISSUE TITLE
Spread Trend should change to State wise trend when a particular state is selected 

### ISSUE THREAD

**Issue by samratthetechwiz** [covid19india/covid19india.github.io#816] opened 2020-04-08 20:00 UTC
**Is your feature request related to a problem? Please describe.**
As of now when we select a state, the map changes to that state but the Spread Trend remains as of the country.

**Describe the solution you'd like**
When a state is selected, Spread Trend should show the trend of that particular state.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jeremyphilemon** [comment] 2020-04-09 02:58
Duplicate of #80

**Closed as completed by jeremyphilemon** 2020-04-09 02:58 UTC
Labels: Status: Review Needed
