### ISSUE TITLE
Active Recovered Deceased count is not displayed after state is selected

### ISSUE THREAD

**Issue by gosharmaa** [covid19india/covid19india.github.io#247] opened 2020-03-27 20:23 UTC
**Describe the bug**
Active Recovered Deceased count is not displayed after state is selected

**To Reproduce**
1. Go to Maharashtra in the map
2. Click on different cities 
3. Notice that Active Recovered Deceased count is not getting updated

**Expected behavior**
Information should get updated correctly

**Screenshots**
![Screenshot_20200328-015015](https://user-images.githubusercontent.com/62764438/77797236-bdcdae00-7096-11ea-92c3-17b98fad99b8.jpg)

**Comment by jeremyphilemon** [comment] 2020-03-27 22:57
The district map support was a recent feature addition! We're only showing "confirmed" data as of now hence the "NA", but once we're sure with our datapoints at a district level granularity, we'll add those datapoints.

@JunaidBabu @sudevschiz word on when we'll be supporting district datapoints?

**Comment by JunaidBabu** [comment] 2020-03-28 08:52
> @JunaidBabu @sudevschiz word on when we'll be supporting district datapoints?

Not any time soon. We should remove Active/Recovered/Decease after selecting state

**Comment by anilgupta1591** [comment] 2020-03-28 11:06
How can contribute or how can take ticket ?
Sorry i know this is not proper medium to ask this question but dont know any other source for this like slack channel

**Comment by puneetnsit** [comment] 2020-03-28 12:39
Working on it

**Comment by gaurav7118** [comment] 2020-03-28 13:34
@jeremyphilemon
I have solved the issue locally but not able to create review or push to master. It is showing unable to access master.

**Comment by JunaidBabu** [comment] 2020-03-28 13:57
This cannot be fixed because we do not have the data at district level. Closing this issue.

**Closed as completed by JunaidBabu** 2020-03-28 13:57 UTC
Labels: Priority: Critical, Status: Available

**Comment by jeremyphilemon** [comment] 2020-03-28 22:37
@anilgupta1591 head over to the issues section, pick any accepted issue and open a PR :)
