### ISSUE TITLE
Make `spread trends` center aligned on mobile devices

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#1173] opened 2020-04-16 14:19 UTC
![IMG_20200416_194057](https://user-images.githubusercontent.com/27947066/79467047-f9ff8900-801a-11ea-9c27-0104f35e1462.jpg)

1. Why not Make selected are center aligned for mobile devices?
2. It's a little bit confusion about scale mode label (do we really need to tell ?)
3. Toggling switches are too small to tap. Why not allow tap on their label too?

**Comment by jeremyphilemon** [comment] 2020-04-16 15:05
> 1. Why not Make selected are center aligned for mobile devices?

Because readability is better when things are aligned from left to right.

> 2. It's a little bit confusion about scale mode label (do we really need to tell ?)

I don't see where the confusion is, it could help if you could explain what the issue might be.

> 3. Toggling switches are too small to tap. Why not allow tap on their label too?

Duplicate of #895 

Thanks!

**Closed as completed by jeremyphilemon** 2020-04-16 15:05 UTC
Labels: Status: Review Needed
