### ISSUE TITLE
Add Visitor count in the home page ->https://www.covid19india.org/

### ISSUE THREAD

**Issue by Zindra** [covid19india/covid19india.github.io#898] opened 2020-04-10 10:15 UTC
Add Visitor count in the home page i.e., https://www.covid19india.org/

**Acceptance criteria :-**
Adding a visitor count will help them to rely on these data easily. You know what I mean, right !  

**Enhancement or Upgrade :-**
_Total visitor / Daily visitor / Currently active or using_

![image](https://user-images.githubusercontent.com/30254595/78983527-0169f280-7b42-11ea-83ea-9703f919990c.png)

**Comment by shuklaayush** [comment] 2020-04-10 12:42
I don't see how this is relevant.

**Comment by Zindra** [comment] 2020-04-10 15:37
Hi @shuklaayush , 
The use of this counter is to let the user know how many people are seeing this and as per simple rating-review system logic that user will follow this website data over others.

**Comment by bee-rickey** [comment] 2020-04-11 07:42
Closing this. Doesn't add any value towards the cause.

**Closed as completed by bee-rickey** 2020-04-11 07:42 UTC
Labels: wontfix

**Comment by Zindra** [comment] 2020-04-12 10:21
@jeremyphilemon can you please have a look at this ? I still believe this is relevant.

**Comment by sudevschiz** [comment] 2020-04-12 10:34
> Adding a visitor count will help them to rely on these data easily. **You know what I mean, right !**

No. Could you explain?

**Comment by Zindra** [comment] 2020-04-12 10:43
@sudevschiz Thanks for replying.

The use of this counter is to let the user know how many people are seeing this and as per simple rating-review system logic that user will follow this website data over others. 
It is a common practice now-a-days to do what others are doing . That is why we have TRENDING in every app.
