### ISSUE TITLE
Synchronisation of daywise count is missing between main statistics, and the total of state-wise statistics. Refer to the attached screenshot. (Confirmed, Active, Recovered, and Deceased counts)

### ISSUE THREAD

**Issue by chintu8104** [covid19india/covid19india.github.io#168] opened 2020-03-26 11:14 UTC
![Screenshot_20200326-163955__01](https://user-images.githubusercontent.com/18171611/77640729-ea8fa180-6f80-11ea-8c5a-bd607de9225b.jpg)
![Screenshot_20200326-163950__01](https://user-images.githubusercontent.com/18171611/77640736-ec596500-6f80-11ea-8de4-70519302238e.jpg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amit88265** [comment] 2020-03-26 14:07
would love to fix this issue. Please assign this issue to me

**Comment by amit88265** [comment] 2020-03-26 14:58
After inspecting a bit I found the issue is on the backend side. Data coming from the backend is not consistent.

**Comment by JunaidBabu** [comment] 2020-03-27 10:10
Thanks for the report. This issue is being discussed and worked on here #168

Closing this item

**Closed as completed by JunaidBabu** 2020-03-27 10:10 UTC
Labels: Duplicate
