### ISSUE TITLE
Recovered and Deceased graph on top should be uniform

### ISSUE THREAD

**Issue by vivekvroy** [covid19india/covid19india.github.io#1027] opened 2020-04-13 05:21 UTC
The two line graphs of recovered and deceased on top, looks like a straight line.
I think it is in sync with confirmed and active cases.
There is no clear curve for these two attributes and needs to be differentiated with confirmed and active.

**Comment by aswaathb** [comment] 2020-04-13 06:24
@vivekvroy think you want different y-axis limits for the recovered and deceased graphs. In which case this issue is a duplicate of #722 (which has been closed)

**Comment by vivekvroy** [comment] 2020-04-13 09:10
Yes that's correct, when you say it is closed, can't that be updated or is the work is in progress now?

**Comment by jaibatrik** [comment] 2020-04-18 05:30
#904 tries to address this issue.

**Comment by shuklaayush** [comment] 2020-04-22 18:09
Closing due to inactivity.

**Closed as completed by shuklaayush** 2020-04-22 18:09 UTC
