### ISSUE TITLE
% of Tested vs Positive would give information about what proportion is affected

### ISSUE THREAD

**Issue by snachiap** [covid19india/covid19india.github.io#1123] opened 2020-04-15 11:55 UTC
**Is your feature request related to a problem? Please describe.**
For example, some states have higher number of positive cases, but it is proportional to how many have been tested. 400 affected out of 10000 tested is much less than 100 affected out of 500.

**Describe the solution you'd like**
Having another column in the home page giving proportionality would be helpful

**Comment by tannakartikey** [comment] 2020-04-15 13:11
@snachiap duplicate of https://github.com/covid19india/covid19india-react/issues/945

**Closed as completed by tannakartikey** 2020-04-15 13:11 UTC
Labels: Status: Review Needed
