### ISSUE TITLE
No sitemap available (SEO)

### ISSUE THREAD

**Issue by abhishekakade** [covid19india/covid19india.github.io#1110] opened 2020-04-15 07:05 UTC
**Describe the bug**
Sitemap XML will help increase the reach and improve crawling and overall SEO.

**Comment by tannakartikey** [comment] 2020-04-15 07:23
@abhishekakade the issue is duplicate of https://github.com/covid19india/covid19india-react/issues/262

Please edit your PR description to point the actual issue as well.

Thanks.

**Closed as completed by tannakartikey** 2020-04-15 07:23 UTC
Labels: Status: Review Needed

**Comment by abhishekakade** [comment] 2020-04-15 07:44
@tannakartikey, I searched for 'SEO' issues but didn't find any related to this so I created a new one.
