### ISSUE TITLE
Some UTs are missing

### ISSUE THREAD

**Issue by vairavlaksh** [covid19india/covid19india.github.io#233] opened 2020-03-27 13:54 UTC
**Describe the bug**
Union Territories like Chandigarh, Lakshwadeep, Dadra and Nagar Haveli and Daman and Diu are missing in the list.

**To Reproduce**
1. Go to 'https://www.covid19india.org'
2. See the above mentioned UTs are not in the list

**Expected behavior**
It has to show all the states and UTs of India

**Desktop (please complete the following information):**
 - OS: All OS
 - Browser Chrome, Safari, IE, Firefox
 - Version All Versions

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Comment by Rajesh-Narayanappa87** [comment] 2020-03-27 14:17
@vairavlaksh : Chandigarh is showing up in list and rest are not showing because api is not having data.
Not a front end issue to fix...

**Comment by sudevschiz** [comment] 2020-03-27 14:29
They are missing in the list because they don't have any confirmed cases yet. 

I confirmed that they are part of the larger list in the Sheet. Closing.

**Closed as completed by sudevschiz** 2020-03-27 14:29 UTC
Labels: Status: Review Needed
