### ISSUE TITLE
Add deceased vs age graph in deep dive section.

### ISSUE THREAD

**Issue by tkkhhaarree** [covid19india/covid19india.github.io#1037] opened 2020-04-13 13:36 UTC
Please add a graph for number of people deceased vs their age in the deep dive section.

**Comment by yash-rajpal** [comment] 2020-04-13 14:01
I would very much like to work on this issue, but I checked the API for deaths. It doesn't have the age of all dead people.

**Comment by strikertanmay** [comment] 2020-04-13 14:05
Duplicate issue (https://github.com/covid19india/covid19india-react/issues/967) and PR for this issue were already made.

**Comment by sudevschiz** [comment] 2020-04-19 00:37
Duplicate of #967

**Closed as completed by sudevschiz** 2020-04-19 00:37 UTC
Labels: Duplicate, Deep-Dive
