### ISSUE TITLE
Time Series Per State

### ISSUE THREAD

**Issue by madhurrajn** [covid19india/covid19india.github.io#713] opened 2020-04-06 00:44 UTC
At present the time series graph shows daily case update for the entire country.  Would it be possible to enhance to update the time series of daily case per state as and when the state is selected. 

Eventually enhance to per district within state.

**Comment by shuklaayush** [comment] 2020-04-06 03:32
Duplicate of #564

**Closed as completed by shuklaayush** 2020-04-06 03:32 UTC
