### ISSUE TITLE
District wise Active, Recovered, and  Death report

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#679] opened 2020-04-05 08:42 UTC
**Is your feature request related to a problem? Please describe.**
As of now only state-wise Active, recovered and death report is displayed. I have seen the data source and it has District wise recovered and death data. The number is slightly increasing so for batter understanding can we include Active, Recovered and Death count for District as well.  

- In addition to that daily increase-count would be helpful more to granular analysis.

<img width="652" alt="Screenshot 2020-04-05 at 2 11 04 PM" src="https://user-images.githubusercontent.com/21332852/78470465-6b9c2500-7747-11ea-8162-e786666b8abd.png">

**Comment by shuklaayush** [comment] 2020-04-05 08:59
Duplicate of #675

**Closed as completed by shuklaayush** 2020-04-05 08:59 UTC
Labels: Status: Review Needed

**Comment by DhiralKaniya** [comment] 2020-04-05 09:16
@shuklaayush:- UI Behavior is different here. 
Asking to have data in the table view. #675 issue locked to have data in a summary view. 

Data requirement in this API:- https://api.covid19india.org/state_district_wise.json
I would like to take this.

**Comment by shuklaayush** [comment] 2020-04-05 09:33
Hey @DhiralKaniya, I understand that you want to have it displayed on the table. But the thing is that, for us, it doesn't really matter. If we have the data, we can display it anywhere. The problem right now is that we don't the district level data for active, recovered and deaths. You can verify this in the API that you've linked.
