### ISSUE TITLE
Adding a Yesterday stats button

### ISSUE THREAD

**Issue by ShivS01** [covid19india/covid19india.github.io#1779] opened 2020-05-05 06:40 UTC
Hi, I'd like to recommend a yesterday statistics button, which shows stats of yesterday statewise/district wise.

kinda similar to https://www.worldometers.info/coronavirus/

![Screenshot_19](https://user-images.githubusercontent.com/43378694/81040573-4545e280-8ec9-11ea-9da4-49c60e617883.png)

Loving the website, amazing work, keep it up! Hopefully I can contribute, learning react/express myself. :)

**Comment by vipul1999** [comment] 2020-05-05 06:46
I was in the middle of the opening this issue but just saw it appeared already. Good Work. Hopefully, this issue gonna reviewed soon.

**Comment by pratikgupta123** [comment] 2020-05-05 09:05
+1
I was going to open this feature request.

**Comment by bee-rickey** [comment] 2020-05-05 10:53
Since we already have a delta per district/state, what's the advantage of this yesterday's data?

**Comment by ShivS01** [comment] 2020-05-05 11:10
> Since we already have a delta per district/state, what's the advantage of this yesterday's data?

The graphs are good, but with the yesterday's button, one could simply see the numbers in the same list on the home screen. Just saves time and keeps stuff clutter free who don't want to go too deep into stats.

Though it's not necessary, but I think it's a convenient feature to have.

**Comment by ShivS01** [comment] 2020-05-05 11:13
![Screenshot_21](https://user-images.githubusercontent.com/43378694/81060028-4a1d8d00-8eef-11ea-8e9d-a8da1c132759.png)

Like if a person clicks the button, the counters beside the state/district  attributes render yesterday's data.
It gives a good idea if you see yesterday's data as it summarizes the whole day's data, rather than today's data which is updated dynamically.

Yesterday's data is static, gives more idea of the growth in short and concise way I think, so that is why it's probably a good idea to have one.

**Comment by pratikgupta123** [comment] 2020-05-06 05:25
Adding to @ShivS01 's point.
A Yesterday button will provide a way to see the District wise numbers for yesterday which is not present in the state page.

**Comment by pratikgupta123** [comment] 2020-05-14 07:33
@bee-rickey 
Hoping that this feature will be added soon.

**Comment by bee-rickey** [comment] 2020-05-14 20:14
@pratikgupta123 I’m not convinced. We already have the delta arrow per district. We have delta arrow per state. How does showing yesterday’s number help? Example, UP has more than 70 districts. If we provide a toggle to yesterday’s numbers you’ll see 70*3 data points. Will keep this open and request other mods to weigh in. @sudevschiz @jeremyphilemon

**Comment by ayush000** [comment] 2020-05-29 14:30
It is nice to see yesterday's delta. It gives a static point of reference. And some people might find it useful to compare deltas of similarly affected states.

E.g. If I were to compare Maharashtra & Tamil Nadu's rate of recovery, it will be more convenient to compare yesterday's delta, because cases for the same day don't get reported at the same frequency. Now, you can go to individual state and check their detailed graphs, but checking for yesterday's delta quickly might be helpful for comparing 3-4 states.

Another example: If I missed checking the dashboard yesterday night, and want to check the final deltas for yesterday the next morning I wake up.

Let me know if I can help on this. I'm a JS developer, and can work on this over the weekend.

cc @bee-rickey @sudevschiz @jeremyphilemon

**Comment by jeremyphilemon** [comment] 2020-06-01 21:42
Closed by #2009 after introducing the timeline :)

**Closed as completed by jeremyphilemon** 2020-06-01 21:42 UTC
Labels: Status : Question

**Comment by pratikgupta123** [comment] 2020-06-02 05:38
@jeremyphilemon the timeline feature is awesome!

Just one observation, the state number change as I move in the timeline but the district number change only when I hover over them or the state map. Is this intended behaviour? or should they change automatically too?

**Comment by ayush000** [comment] 2020-06-02 11:26
Amazing work!

**Comment by ShivS01** [comment] 2020-06-02 14:30
> Closed by #2009 after introducing the timeline :)

Cool feature. 
Is the feature only for the landing page and not available to state pages?
