### ISSUE TITLE
Death report for every district wise in all state according to new case column

### ISSUE THREAD

**Issue by agnivesh3006** [covid19india/covid19india.github.io#1129] opened 2020-04-15 16:16 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudevschiz** [comment] 2020-04-19 00:48
Duplicate of #888

**Closed as completed by sudevschiz** 2020-04-19 00:48 UTC
Labels: Duplicate, Data
