### ISSUE TITLE
Graphs should be independent of system time

### ISSUE THREAD

**Issue by quantumfrost** [covid19india/covid19india.github.io#1100] opened 2020-04-14 23:40 UTC
**Describe the bug**
The graphs change depending on what the system time is set to. This means different graphs are shown in different timezones, and some timezones show outdated information.

**To Reproduce**

1. Set system date to yesterday's date
2. Go to the website
3. Look at the graphs
4. Revert system date
5. Refresh website
6. Compare the graphs

**Expected behavior**
The graphs should always show the latest information available, regardless of the user's timezone or system time.

**Screenshots**
Both screenshots taken within 1 minute of each other:

![System date April 15 2020](https://user-images.githubusercontent.com/4280297/79283914-4023e380-7e87-11ea-9a33-e98db40e33b5.png)

![System date April 14](https://user-images.githubusercontent.com/4280297/79283953-5df14880-7e87-11ea-99dc-6693d1e5606a.png)

**Smartphone (please complete the following information):**

- Device: Pixel 3 XL
- OS: Android 10
- Browser: Chrome
- Version: 80

**Comment by sudevschiz** [comment] 2020-04-15 04:02
Yes, all graphs should be based out IST. Marking this available.

**Comment by faisal3389** [comment] 2020-04-15 09:39
I would like to work on this. Please assign this to me

**Comment by tannakartikey** [comment] 2020-04-15 12:54
@faisal3389 all yours!

**Comment by jeremyphilemon** [comment] 2020-04-16 09:37
@sudevschiz Doesn't this have to do with the api side? The timeseries graphs don't refer to the system time at all though?

**Comment by sudevschiz** [comment] 2020-04-19 01:52
@jeremyphilemon interesting. The data in the sheet adds a new row for "yesterday" at around 12:05AM. If system times doesn't matter,I am wondering what happened in the steps to reproduce that OP mentioned

**Comment by quantumfrost** [comment] 2020-04-20 00:08
@sudevschiz can you not reproduce it?

**Comment by shuklaayush** [comment] 2020-04-22 18:13
Is this still happening? Might be because of the date checks in the utility functions

**Comment by aniketnk** [comment] 2020-04-22 21:02
The bug seems to occur in the validateCTS function
https://github.com/covid19india/covid19india-react/blob/492bafe0dccfc8baeb4264040ad1f87422fd8fff/src/utils/commonfunctions.js#L39-L57
The variable `today` gets the device time and then the hours are set to 0. While returning the data, it is filtered with the condition `new Date(d.date + year) < today;` which will return false if the most recent date fetched is greater than device date(which may be in a different time zone). An easy fix would be to remove this filter. Should I submit a PR?

**Comment by shuklaayush** [comment] 2020-04-22 23:24
@aniketnk We can't remove the filter since we don't want to plot the data for today (in IST). You'll have to make the date check timezone independent. Also, the same modification has to be done in other API parsing functions.

**Comment by aniketnk** [comment] 2020-04-23 08:46
@shuklaayush Oh okay. That makes sense. 
I think I found a fix for this using the `moment` library. Will implement it and open a PR. I'll also make the modifications in the other API parsing functions.

**Closed as completed** 2020-04-24 14:56 UTC
Labels: Status : Question
