### ISSUE TITLE
Country wide over all cases need to be reported

### ISSUE THREAD

**Issue by prablr79** [covid19india/covid19india.github.io#1068] opened 2020-04-14 05:28 UTC
India wide cases at over all is not projected, hence TESTED data shows Nil or - in the Home page.  if that give more clarity this tool data make sense.

for more clarity please reply, I will comment on this issue

**Comment by prablr79** [comment] 2020-04-14 05:35
every state wise Tested details shown much clearer, which you have some data back up from State govt report directly opening as .pdf file.  Which is good, the same required at Nation level.

**Comment by sudevschiz** [comment] 2020-04-14 05:59
Duplicate of #1013

**Closed as completed by sudevschiz** 2020-04-14 05:59 UTC
Labels: Status: Review Needed
