### ISSUE TITLE
Show spread trend graph for each state

### ISSUE THREAD

**Issue by sandeephegde16** [covid19india/covid19india.github.io#448] opened 2020-04-01 09:42 UTC
**Is your feature request related to a problem? Please describe.**
It is good to show spread trends for each state to track statewise data. If suppose any state has flat curve, similar containment and testing measures can be successfully implimented in other states as well.

**Describe the solution you'd like**
Upon clicking state wise map, show state wise spread trend below.

**Comment by shuklaayush** [comment] 2020-04-01 09:58
Duplicate of #219

**Closed as completed by shuklaayush** 2020-04-01 09:58 UTC
Labels: Status: Review Needed
