### ISSUE TITLE
Stats for Meghalaya and Nagaland should have counts

### ISSUE THREAD

**Issue by kabzzy** [covid19india/covid19india.github.io#938] opened 2020-04-11 07:22 UTC
States with zero confirmed cases, Meghalaya and Nagaland, shows no count for number of tests done. There should be either a note somewhere on the site to inform what the blank value means - NO tests done or or the number of  tests will be updated only when a confirmed case is found.

Alternatively, show the  number of tests done and zero for other states.

**Comment by sudevschiz** [comment] 2020-04-11 07:36
Yes. This is the expected behaviour. Even if no confirmed cases are present, testing data should be reported.

**Comment by kabzzy** [comment] 2020-04-11 07:41
> Yes. This is the expected behaviour. Even if no confirmed cases are present, testing data should be reported.

That's what I mean. They are missing right now. Here's Meghalaya for example. Same is the case with Sikkim. Nagaland on other hand, started showing the "Tested" count.

![Capture](https://user-images.githubusercontent.com/3241528/79038312-fe303e80-7bf5-11ea-9ac5-31683ff6032f.PNG)

**Comment by jeremyphilemon** [comment] 2020-04-24 23:04
Closing since the states in question now show test numbers.

**Closed as completed by jeremyphilemon** 2020-04-24 23:04 UTC
Labels: Data
