### ISSUE TITLE
In mobile, touch event is triggered while scrolling through timeseries graph

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1224] opened 2020-04-17 15:30 UTC
**Describe the bug**
In mobile, touch event is triggered on the graphs making it changing always while scrolling through timeseries graph.

**To Reproduce**
Steps to reproduce the behavior (Mobile):

1. Go to Home
2. Go down to timeseries graphs
3. Scroll up and down 

**Expected behavior**
Scrolling through the timeseries graph should not affect the graphs.

**Comment by shuklaayush** [comment] 2020-04-17 22:25
Can you elaborate?

**Comment by nayakrahul** [comment] 2020-04-17 22:35
`
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11428805/79619122-9adc6a00-8129-11ea-9b0e-fe50c6f9b399.gif)
`

Notice how the dots in graphs moves while scrolling across the graphs.

**Comment by nayakrahul** [comment] 2020-04-17 22:36
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11428805/79619211-decf6f00-8129-11ea-92a3-29d75dfbb7af.gif)
Notice how the dots in graphs move while scrolling across the graphs

**Comment by shuklaayush** [comment] 2020-04-18 07:18
@nayakrahul This functionality is there to view previous data by horizontally scrolling the time series. It resets when you lift your finger. I'm sorry, I don't understand what the problem is. Is it interfering with normal scrolling for you?

**Comment by nayakrahul** [comment] 2020-04-18 09:51
@shuklaayush Thing is that when we scroll up and down on mobile devices, we don't move our finger at exact 90 degree, it involves a bit of horizontal scrolling too. So that's why when you scroll up and down, the dots in timeseries graph change too. I don't know if you understand or not. In the gif, you can see that i am not doing horizontal scrolling rather i am scrolling up and down but the dots are moving in the graphs to show data for other dates.

**Comment by shuklaayush** [comment] 2020-04-18 10:58
Okay, I see your point. But we need an alternative interaction then. A lot of people find it useful to scroll horizontally across the chart to view data from earlier dates.

**Comment by nayakrahul** [comment] 2020-04-18 14:21
If there is upward or downward movement of page, we should keep the charts static.

**Comment by shuklaayush** [comment] 2020-04-18 14:44
Okay, can you fix this? I'll assign it to you then

**Comment by nayakrahul** [comment] 2020-04-18 18:19
@shuklaayush Actually, the problem is related to d3.js . The same problem can also be seen when we zoom the page  in or out on mobile devices by putting fingers on the timeseries charts.
Since there is an event on touch move, whenever we scroll or zoom by putting fingers on svg charts, the touchmove event gets trigerred.

**Comment by nayakrahul** [comment] 2020-04-18 18:32
@shuklaayush Anyhow I have made a hack to prevent charts from changing while scrolling but I don't know if it is a complete solution.

**Closed as completed** 2020-04-23 09:55 UTC
Labels: Status : Question, Status: Review Needed
