### ISSUE TITLE
Daily & Cumulative chart - Statewise

### ISSUE THREAD

**Issue by petroanveshak** [covid19india/covid19india.github.io#449] opened 2020-04-01 09:45 UTC
**Is your feature request related to a problem? Please describe.**
Daily & Cumulative chart - Statewise

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shuklaayush** [comment] 2020-04-01 09:58
Duplicate of #219

**Closed as completed by shuklaayush** 2020-04-01 09:58 UTC
Labels: Status: Review Needed
